version: '3.3'

services:
    server1:
        container_name: server1
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - SERVER_PORT=8000
        networks:
            - app_network

    server2:
        container_name: server2
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - SERVER_PORT=8000
        networks:
            - app_network

    server3:
        container_name: server3
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - SERVER_PORT=8000
        networks:
            - app_network

    load_balancer:
        build: 
            context: ./nginx
        ports:
            - '3000:80'
        depends_on:
            - server1
            - server2
            - server3
        networks:
            - app_network

networks:
    app_network:
        driver: bridge